### ISSUE TITLE
this.bluetoothle.initializePeripheral(...).subscribe is not a function

### ISSUE THREAD

**Issue by maske94** [somq/ionic-plugin-bluetoothle#5] opened 2018-08-28 15:53 UTC
Hi,

Im working with Android and after having installed the new version 1.0.0 my code crashes.
Apparently, with this new version, the method initializePeripheral() should return an Observable:

```
  /**
   * @name initializePeripheral
   * @description Initialize Bluetooth on the device. Must be called before anything else.
   * Callback will continuously be used whenever Bluetooth is enabled or disabled.
   * @param {InitPeripheralParams} [params]
   * @returns {Observable<InitializeResult>}
   */
  @Cordova({callbackOrder: 'reverse'})
  initializePeripheral(params?: InitPeripheralParams ): Observable<InitializeResult> {
    return;
  }
```

Therefore, in my code I called the method subscribe() on the returned object:

```
      this.bluetoothle.initializePeripheral(peripheralParams).subscribe(
        result => console.log('Ble initialization result: ', result),
        error => console.log('Ble initialization error: ', error));
```

At a first place, the code compiles and is installed on the device.
But then when I start the app I get this error:

<img width="586" alt="screen shot 2018-08-28 at 17 19 16" src="https://user-images.githubusercontent.com/17084635/44732852-87106a00-aae6-11e8-9349-444d1d1912f3.png">

I printed what is returned by the method initializePeripheral() and the result seems to be a Promise instead of an Observable (as it was in the previous versions of this plugin) :

<img width="558" alt="screen shot 2018-08-28 at 17 31 33" src="https://user-images.githubusercontent.com/17084635/44733621-4285ce00-aae8-11e8-956e-8d422a20d0d4.png">

Of course the Promise object doesn't have a subscribe() method and that's the reason of the crash.

Do you have any idea about what could be the problem?

Hope the explanation was sufficiently clear.
Thanks a lot in advance for any help.

**Comment by somq** [comment] 2018-08-28 16:51
Can you please double check that when you ran ``npm install ionic-plugin-bluetoothle@1.0.0`` postinstall script (./install.js) ran properly and overwrote @ionic-native/bluetooth-le folder?

If not, you can manually re-run the script (``node node_modules/ionic-plugin-bluetoothle/install.js``) or just copy-paste the dist content (node_modules/ionic-plugin-bluetoothle/dist/bluetooth-le folder) in node_modules/@ionic-native folder.

The dist folder has probably not been copied to the @ionic-native folder and you are still running v0.0.3 even though the lib have been installed through npm.

Also, are you working with Ionic v3 or v4? Because Ionic team recently [published the plugin](https://www.npmjs.com/package/@ionic-native/bluetooth-le). Not sure if a release has been done already for Ionic v3 but I can confirm it has been for v4 because I'm using it since yesterday. Just to say, it should be released very soon for v3 if it has not been yet...

**Comment by maske94** [comment] 2018-08-29 09:16
Hi @somq  and thanks for the quick reply.

Yes the postinstall script runs properly and it copies the files correctly:

<img width="362" alt="screen shot 2018-08-29 at 10 39 53" src="https://user-images.githubusercontent.com/17084635/44776236-eec2c580-ab77-11e8-8a50-6c0295d67c28.png">

I also checked the folders content and it's actually the same.
Moreover, I think that it's not possible that I'm still running the version 0.3.0 since during the building phase the code compiles and the IDE recognise that the method initializePeripheral() returns an Observable instead of a Promise.

Is like if the code "interface" and the "implementation" are not aligned.

By the way, I'm using ionic v4, I tried to install the native plugin but im facing other problems.
Thanks a lot for the help.

**Comment by maske94** [comment] 2018-08-29 09:27
I eventually managed to make it work with the [native ionic plugin](https://www.npmjs.com/package/@ionic-native/bluetooth-le), however I got the same error: 

<img width="592" alt="screen shot 2018-08-29 at 11 26 05" src="https://user-images.githubusercontent.com/17084635/44778890-58de6900-ab7e-11e8-883a-89593b56478f.png">

Any idea ?

Thanks for supporting.

**Comment by somq** [comment] 2018-08-29 10:30
What's your import line?

**Comment by somq** [comment] 2018-08-29 10:41
Hi @maske94,
I tested the ionic plugin from scratch and you are right, there is a missing param (should be ``@Cordova({ callbackOrder: 'reverse', observable: true })``) in the [cordova definition file](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/bluetooth-le/index.ts#L896). Which causes the observable to be broken.

Thanks for your feedback, I'm gonna make a PR this afternoon on the ionic-native repo. In the meantime you can manually compile the plugin to fix this bug.

**Comment by maske94** [comment] 2018-08-29 12:16
Hello @somq ,

Sooolved!
I edited that file and it temporary solved the problem.
Thanks god, I struggled for 1 day for this. Now let's wait for the definitive fix.

Thanks again for your precious help.

ps: 
Congrats for your work on this plugin. Keep it ip :)

**Comment by somq** [comment] 2018-08-29 12:21
Thanks @maske94 and of course your welcome.
I will make the PR asap (lot of pending work here ;p)

If you find any other mistakes/misfunctionnings feel free to open a new issue or even prepare a PR.
I'm closing this one.

**Closed as completed by somq** 2018-08-29 12:21 UTC
